name: Deploy Frontend to Azure App Service (zip-run)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate .env.production from secrets
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env.production

      - name: Prune to production deps
        run: npm prune --omit=dev

      - name: Create release.zip
        run: |
          mkdir -p .release
          cp -a .next public package.json package-lock.json next.config.js .env.production .release/
          # runtime に必要な node_modules を同梱
          cp -a node_modules .release/node_modules
          cd .release
          zip -yr ../release.zip .
          cd ..
          ls -lh release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip