name: Deploy Frontend to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Create production env file
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env.production
          cat .env.production

      - name: Install deps & Build
        run: |
          npm ci
          npm run build

      - name: Prepare deploy artifact (include node_modules)
        run: |
          rm -rf deploy && mkdir -p deploy
          cp -r .next deploy/.next
          cp -r public deploy/public
          cp -r node_modules deploy/node_modules
          cp package.json deploy/package.json
          cp package-lock.json deploy/package-lock.json || true
          [ -f .env.production ] && cp .env.production deploy/.env.production || true
          [ -f next.config.js ] && cp next.config.js deploy/ || true

      - name: Zip artifact
        run: |
          cd deploy
          zip -r ../frontend.zip ./*
          cd ..

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: frontend.zip