name: Deploy Frontend to Azure App Service (standalone-flat)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (Next.js standalone)
        run: npm run build

      # ここが肝：standalone の中身を release/ 直下にフラット配置
      - name: Create release folder (flatten)
        run: |
          rm -rf release
          mkdir -p release
          # 1) standalone の中身を release 直下へ（= ルート直下に server.js が来る）
          cp -R .next/standalone/* release/
          # 2) 静的ファイルと BUILD_ID は ./next に揃える
          mkdir -p release/.next
          cp -R .next/static release/.next/static
          cp .next/BUILD_ID release/.next/BUILD_ID
          # 3) public も同梱
          cp -R public release/public || true
          # 4) ルートの package.json（起動時に Next が参照することがあるため）
          cp package.json release/package.json
          # 5) 実行時に使う .env.production を生成（GitHub Secrets から）
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > release/.env.production

      - name: Show release layout (debug)
        run: |
          echo "== release top =="
          ls -la release | sed -n '1,200p'
          echo "== release/.next =="
          ls -la release/.next | sed -n '1,200p'
          echo "== server.js path =="
          test -f release/server.js && echo "[OK] server.js exists at release/server.js" || (echo "[NG] server.js missing" && exit 1)
          echo "== BUILD_ID =="
          cat release/.next/BUILD_ID || true

      - name: Zip artifact
        run: |
          cd release
          zip -r ../release.zip .
          cd -
          ls -lh release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          slot-name: 'production'
          package: release.zip