name: Deploy Frontend to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # Install dependencies to ensure clean package-lock.json
      - name: Install deps
        run: npm ci

      # Optional: Build locally (Oryx can also build on App Service)
      - name: Build
        run: npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .   # Deploy root directory with package.json for Oryx

      - name: Deployment Status
        run: |
          echo "✅ Deployment completed successfully!"
          echo "🌐 App should be available at: https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net"
          echo "📝 Using Oryx build flow with npm start -p $PORT"